
.PHONY: generate-values
generate-values:
	@echo "# This file was autogenerated." > charts/kubewarden/values.yaml
	@echo >> charts/kubewarden/values.yaml
	@cat charts/kubewarden/chart-values.yaml >> charts/kubewarden/values.yaml
	@echo "# This file was autogenerated." > charts/allowed-fsgroups-psp/values.yaml
	@echo >> charts/allowed-fsgroups-psp/values.yaml
	@cat common-values.yaml charts/allowed-fsgroups-psp/chart-values.yaml >> charts/allowed-fsgroups-psp/values.yaml
	@echo "# This file was autogenerated." > charts/allowed-proc-mount-types-psp/values.yaml
	@echo >> charts/allowed-proc-mount-types-psp/values.yaml
	@cat common-values.yaml charts/allowed-proc-mount-types-psp/chart-values.yaml >> charts/allowed-proc-mount-types-psp/values.yaml
	@echo "# This file was autogenerated." > charts/allow-privilege-escalation-psp/values.yaml
	@echo >> charts/allow-privilege-escalation-psp/values.yaml
	@cat common-values.yaml charts/allow-privilege-escalation-psp/chart-values.yaml >> charts/allow-privilege-escalation-psp/values.yaml
	@echo "# This file was autogenerated." > charts/apparmor-psp/values.yaml
	@echo >> charts/apparmor-psp/values.yaml
	@cat common-values.yaml charts/apparmor-psp/chart-values.yaml >> charts/apparmor-psp/values.yaml
	@echo "# This file was autogenerated." > charts/capabilities-psp/values.yaml
	@echo >> charts/capabilities-psp/values.yaml
	@cat common-values.yaml charts/capabilities-psp/chart-values.yaml >> charts/capabilities-psp/values.yaml
	@echo "# This file was autogenerated." > charts/disallow-service-loadbalancer/values.yaml
	@echo >> charts/disallow-service-loadbalancer/values.yaml
	@cat common-values.yaml charts/disallow-service-loadbalancer/chart-values.yaml >> charts/disallow-service-loadbalancer/values.yaml
	@echo "# This file was autogenerated." > charts/disallow-service-nodeport/values.yaml
	@echo >> charts/disallow-service-nodeport/values.yaml
	@cat common-values.yaml charts/disallow-service-nodeport/chart-values.yaml >> charts/disallow-service-nodeport/values.yaml
	@echo "# This file was autogenerated." > charts/flexvolume-drivers-psp/values.yaml
	@echo >> charts/flexvolume-drivers-psp/values.yaml
	@cat common-values.yaml charts/flexvolume-drivers-psp/chart-values.yaml >> charts/flexvolume-drivers-psp/values.yaml
	@echo "# This file was autogenerated." > charts/host-namespaces-psp/values.yaml
	@echo >> charts/host-namespaces-psp/values.yaml
	@cat common-values.yaml charts/host-namespaces-psp/chart-values.yaml >> charts/host-namespaces-psp/values.yaml
	@echo "# This file was autogenerated." > charts/hostpaths-psp/values.yaml
	@echo >> charts/hostpaths-psp/values.yaml
	@cat common-values.yaml charts/hostpaths-psp/chart-values.yaml >> charts/hostpaths-psp/values.yaml
	@echo "# This file was autogenerated." > charts/ingress/values.yaml
	@echo >> charts/ingress/values.yaml
	@cat common-values.yaml charts/ingress/chart-values.yaml >> charts/ingress/values.yaml
	@echo "# This file was autogenerated." > charts/pod-privileged-policy/values.yaml
	@echo >> charts/pod-privileged-policy/values.yaml
	@cat common-values.yaml charts/pod-privileged-policy/chart-values.yaml >> charts/pod-privileged-policy/values.yaml
	@echo "# This file was autogenerated." > charts/pod-runtime/values.yaml
	@echo >> charts/pod-runtime/values.yaml
	@cat common-values.yaml charts/pod-runtime/chart-values.yaml >> charts/pod-runtime/values.yaml
	@echo "# This file was autogenerated." > charts/readonly-root-filesystem-psp/values.yaml
	@echo >> charts/readonly-root-filesystem-psp/values.yaml
	@cat common-values.yaml charts/readonly-root-filesystem-psp/chart-values.yaml >> charts/readonly-root-filesystem-psp/values.yaml
	@echo "# This file was autogenerated." > charts/safe-annotations/values.yaml
	@echo >> charts/safe-annotations/values.yaml
	@cat common-values.yaml charts/safe-annotations/chart-values.yaml >> charts/safe-annotations/values.yaml
	@echo "# This file was autogenerated." > charts/safe-labels/values.yaml
	@echo >> charts/safe-labels/values.yaml
	@cat common-values.yaml charts/safe-labels/chart-values.yaml >> charts/safe-labels/values.yaml
	@echo "# This file was autogenerated." > charts/seccomp-psp/values.yaml
	@echo >> charts/seccomp-psp/values.yaml
	@cat common-values.yaml charts/seccomp-psp/chart-values.yaml >> charts/seccomp-psp/values.yaml
	@echo "# This file was autogenerated." > charts/selinux-psp/values.yaml
	@echo >> charts/selinux-psp/values.yaml
	@cat common-values.yaml charts/selinux-psp/chart-values.yaml >> charts/selinux-psp/values.yaml
	@echo "# This file was autogenerated." > charts/sysctl-psp/values.yaml
	@echo >> charts/sysctl-psp/values.yaml
	@cat common-values.yaml charts/sysctl-psp/chart-values.yaml >> charts/sysctl-psp/values.yaml
	@echo "# This file was autogenerated." > charts/trusted-repos/values.yaml
	@echo >> charts/trusted-repos/values.yaml
	@cat common-values.yaml charts/trusted-repos/chart-values.yaml >> charts/trusted-repos/values.yaml
	@echo "# This file was autogenerated." > charts/user-group-psp/values.yaml
	@echo >> charts/user-group-psp/values.yaml
	@cat common-values.yaml charts/user-group-psp/chart-values.yaml >> charts/user-group-psp/values.yaml
	@echo "# This file was autogenerated." > charts/verify-image-signatures/values.yaml
	@echo >> charts/verify-image-signatures/values.yaml
	@cat common-values.yaml charts/verify-image-signatures/chart-values.yaml >> charts/verify-image-signatures/values.yaml
	@echo "# This file was autogenerated." > charts/volumes-psp/values.yaml
	@echo >> charts/volumes-psp/values.yaml
	@cat common-values.yaml charts/volumes-psp/chart-values.yaml >> charts/volumes-psp/values.yaml


.PHONY: check-generated-values
check-generated-values: generate-values
	@sh -c 'git diff --exit-code charts || (echo; echo "There are chart differences that have to be checked in"; exit 1)'
