
.PHONY: generate-values
generate-values:
	@echo "# This file was autogenerated." > charts/allowed-fsgroups-psp/values.yaml
	@echo >> charts/allowed-fsgroups-psp/values.yaml
	@cat common-values.yaml charts/allowed-fsgroups-psp/templates/allowed-fsgroups-psp.yaml >> charts/allowed-fsgroups-psp/values.yaml
	@echo "# This file was autogenerated." > charts/allowed-proc-mount-types-psp/values.yaml
	@echo >> charts/allowed-proc-mount-types-psp/values.yaml
	@cat common-values.yaml charts/allowed-proc-mount-types-psp/templates/allowed-proc-mount-types-psp.yaml >> charts/allowed-proc-mount-types-psp/values.yaml
	@echo "# This file was autogenerated." > charts/allow-privilege-escalation-psp/values.yaml
	@echo >> charts/allow-privilege-escalation-psp/values.yaml
	@cat common-values.yaml charts/allow-privilege-escalation-psp/templates/allow-privilege-escalation-psp.yaml >> charts/allow-privilege-escalation-psp/values.yaml
	@echo "# This file was autogenerated." > charts/apparmor-psp/values.yaml
	@echo >> charts/apparmor-psp/values.yaml
	@cat common-values.yaml charts/apparmor-psp/templates/apparmor-psp.yaml >> charts/apparmor-psp/values.yaml
	@echo "# This file was autogenerated." > charts/capabilities-psp/values.yaml
	@echo >> charts/capabilities-psp/values.yaml
	@cat common-values.yaml charts/capabilities-psp/templates/capabilities-psp.yaml >> charts/capabilities-psp/values.yaml
	@echo "# This file was autogenerated." > charts/disallow-service-loadbalancer/values.yaml
	@echo >> charts/disallow-service-loadbalancer/values.yaml
	@cat common-values.yaml charts/disallow-service-loadbalancer/templates/disallow-service-loadbalancer.yaml >> charts/disallow-service-loadbalancer/values.yaml
	@echo "# This file was autogenerated." > charts/disallow-service-nodeport/values.yaml
	@echo >> charts/disallow-service-nodeport/values.yaml
	@cat common-values.yaml charts/disallow-service-nodeport/templates/disallow-service-nodeport.yaml >> charts/disallow-service-nodeport/values.yaml
	@echo "# This file was autogenerated." > charts/flexvolume-drivers-psp/values.yaml
	@echo >> charts/flexvolume-drivers-psp/values.yaml
	@cat common-values.yaml charts/flexvolume-drivers-psp/templates/flexvolume-drivers-psp.yaml >> charts/flexvolume-drivers-psp/values.yaml
	@echo "# This file was autogenerated." > charts/host-namespaces-psp/values.yaml
	@echo >> charts/host-namespaces-psp/values.yaml
	@cat common-values.yaml charts/host-namespaces-psp/templates/host-namespaces-psp.yaml >> charts/host-namespaces-psp/values.yaml
	@echo "# This file was autogenerated." > charts/hostpaths-psp/values.yaml
	@echo >> charts/hostpaths-psp/values.yaml
	@cat common-values.yaml charts/hostpaths-psp/templates/hostpaths-psp.yaml >> charts/hostpaths-psp/values.yaml
	@echo "# This file was autogenerated." > charts/ingress/values.yaml
	@echo >> charts/ingress/values.yaml
	@cat common-values.yaml charts/ingress/templates/ingress.yaml >> charts/ingress/values.yaml
	@echo "# This file was autogenerated." > charts/pod-privileged-policy/values.yaml
	@echo >> charts/pod-privileged-policy/values.yaml
	@cat common-values.yaml charts/pod-privileged-policy/templates/pod-privileged-policy.yaml >> charts/pod-privileged-policy/values.yaml
	@echo "# This file was autogenerated." > charts/pod-runtime/values.yaml
	@echo >> charts/pod-runtime/values.yaml
	@cat common-values.yaml charts/pod-runtime/templates/pod-runtime.yaml >> charts/pod-runtime/values.yaml
	@echo "# This file was autogenerated." > charts/readonly-root-filesystem-psp/values.yaml
	@echo >> charts/readonly-root-filesystem-psp/values.yaml
	@cat common-values.yaml charts/readonly-root-filesystem-psp/templates/readonly-root-filesystem-psp.yaml >> charts/readonly-root-filesystem-psp/values.yaml
	@echo "# This file was autogenerated." > charts/safe-annotations/values.yaml
	@echo >> charts/safe-annotations/values.yaml
	@cat common-values.yaml charts/safe-annotations/templates/safe-annotations.yaml >> charts/safe-annotations/values.yaml
	@echo "# This file was autogenerated." > charts/safe-labels/values.yaml
	@echo >> charts/safe-labels/values.yaml
	@cat common-values.yaml charts/safe-labels/templates/safe-labels.yaml >> charts/safe-labels/values.yaml
	@echo "# This file was autogenerated." > charts/seccomp-psp/values.yaml
	@echo >> charts/seccomp-psp/values.yaml
	@cat common-values.yaml charts/seccomp-psp/templates/seccomp-psp.yaml >> charts/seccomp-psp/values.yaml
	@echo "# This file was autogenerated." > charts/selinux-psp/values.yaml
	@echo >> charts/selinux-psp/values.yaml
	@cat common-values.yaml charts/selinux-psp/templates/selinux-psp.yaml >> charts/selinux-psp/values.yaml
	@echo "# This file was autogenerated." > charts/sysctl-psp/values.yaml
	@echo >> charts/sysctl-psp/values.yaml
	@cat common-values.yaml charts/sysctl-psp/templates/sysctl-psp.yaml >> charts/sysctl-psp/values.yaml
	@echo "# This file was autogenerated." > charts/trusted-repos/values.yaml
	@echo >> charts/trusted-repos/values.yaml
	@cat common-values.yaml charts/trusted-repos/templates/trusted-repos.yaml >> charts/trusted-repos/values.yaml
	@echo "# This file was autogenerated." > charts/user-group-psp/values.yaml
	@echo >> charts/user-group-psp/values.yaml
	@cat common-values.yaml charts/user-group-psp/templates/user-group-psp.yaml >> charts/user-group-psp/values.yaml
	@echo "# This file was autogenerated." > charts/verify-image-signatures/values.yaml
	@echo >> charts/verify-image-signatures/values.yaml
	@cat common-values.yaml charts/verify-image-signatures/templates/verify-image-signatures.yaml >> charts/verify-image-signatures/values.yaml
	@echo "# This file was autogenerated." > charts/volumes-psp/values.yaml
	@echo >> charts/volumes-psp/values.yaml
	@cat common-values.yaml charts/volumes-psp/templates/volumes-psp.yaml >> charts/volumes-psp/values.yaml


.PHONY: check-generated-values
check-generated-values: generate-values
	@sh -c 'git diff --exit-code charts || (echo; echo "There are chart differences that have to be checked in"; exit 1)'