---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: safe-labels
spec:
  module: ghcr.io/kubewarden/policies/safe-labels:v0.1.7
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - "*"
    operations:
    - CREATE
  mutating: false
  settings:
    denied_labels:
    - ''
    mandatory_labels:
    - ''
    constrained_labels:
    - {}
