---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: disallow-service-nodeport
spec:
  module: ghcr.io/kubewarden/policies/disallow-service-nodeport:v0.1.2
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - services
    operations:
    - CREATE
  mutating: false
