---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: sysctl-psp
spec:
  module: ghcr.io/kubewarden/policies/sysctl-psp:v0.1.7
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  mutating: false
  settings:
    forbiddenSysctls:
    - ''
    allowedUnsafeSysctls:
    - ''
