---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: pod-privileged-policy
spec:
  module: ghcr.io/kubewarden/policies/pod-privileged:v0.1.10
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  mutating: false
  settings: {}
