---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: allow-privilege-escalation-psp
spec:
  module: ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  mutating: false
  settings:
    default_allow_privilege_escalation: true
