---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: allowed-fsgroups-psp
spec:
  module: ghcr.io/kubewarden/policies/allowed-fsgroups-psp:v0.1.4
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  mutating: false
  settings:
    rule: ''
    ranges:
    - min: 1000
      max: 2000
