---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: safe-annotations
spec:
  policyServer: default
  module: ghcr.io/kubewarden/policies/safe-annotations:v0.1.1
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - "*"
    operations:
    - CREATE
  mutating: false
  settings:
    denied_annotations:
    - ''
    constrained_annotations:
    - {}
