---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: selinux-psp
spec:
  module: ghcr.io/kubewarden/policies/selinux-psp:v0.1.5
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  mutating: false
  settings:
    MustRunAs:
    - {}
    RunAsAny: false
