---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: volumes-psp
spec:
  module: ghcr.io/kubewarden/policies/volumes-psp:v0.1.6
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  mutating: false
  settings:
    allowedTypes:
    - ''
