---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: pod-runtime
spec:
  module: ghcr.io/kubewarden/policies/pod-runtime:v0.1.4
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  mutating: false
  settings:
    reservedRuntimes:
    - ''
    fallbackRuntime: ''
    defaultRuntimeReserved: true
