apiVersion: v2
name: verify-image-signatures
description: A Helm chart for deploying the verify-image-signatures
icon: https://www.kubewarden.io/images/icon-kubewarden.svg
type: application
home: https://www.kubewarden.io/

version: 0.1.2

appVersion: "v0.1.2"