common:
  policyServer:
    default:
      name: default
      enabled: true

policies:
  enabled: true
  skipNamespaces:
    - calico-system
    - cattle-alerting
    - cattle-fleet-local-system
    - cattle-fleet-system
    - cattle-global-data
    - cattle-global-nt
    - cattle-impersonation-system
    - cattle-istio
    - cattle-logging
    - cattle-monitoring-system
    - cattle-pipeline
    - cattle-prometheus
    - cattle-system
    - cert-manager
    - ingress-nginx
    - kube-node-lease
    - kube-public
    - kube-system
    - kubewarden
    - opentelemetry-operator-system
    - rancher-operator-system
    - security-scan
    - tigera-operator
  defaultPolicyMode: "monitor"