---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ''
metadata:
  name: trusted-repos
spec:
  module: ghcr.io/kubewarden/policies/trusted-repos:v0.1.7
  rules:
  - apiGroups: []
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  mutating: false
  settings:
    registries:
      allow:
      - ''
      reject:
      - ''
    tags:
      reject:
      - ''
    images:
      allow:
      - ''
      reject:
      - ''
